### ISSUE TITLE
no autocomplete (command 'extension.tdCompletesMe.start_server'  not found)

### ISSUE THREAD

**Issue by BjarneJensen** [picturesbyrobots/td-completes-me#7]
Hi I am not getting autocomplete functionality in vs and I see this error `Command 'Touch Designer: Start AutoCompletion Engine' resulted in an error (command 'extension.tdCompletesMe.start_server' not found)` vscode when I try to run the start command. I am inexperienced building extensions myself. Ihave tried disabling other plugins, but I cannot get vscode to converse with touchdesigner. I TD, the tcip dat `says binding socket error access denied` Any tips for where to look to solve the issue?

Thanks

**Comment by picturesbyrobots** [comment]
Thanks for looking at the extension. Looks like you resolved this issue.  Would you mind sharing the steps that you took to resolve this issue and or any thing that I could add to the documentation and or the TS to make it easier for folks who are interested in adding auto completion to their TD projects?

**Comment by BjarneJensen** [comment]
Sure thing! I'll add some info to my github post too if you'd like. I
discovered it was a port issue. Port 1338 was occupied by some other
software (Inventables Easel Driver defaults to 1338). It did not initially
work when I tried to manually configure the port, so I just deleted the
other software for now . So it really was not an issue at all but a good
reminder to check traffic on ports. I learned some stuff about my
configuration and building extensions from source so It was not a loss. And
now this awesome tool works! Great job bringing this to life!

Thanks

**Comment by picturesbyrobots** [comment]
I'm glad to hear you got it working, always fun to get a deep dive into the port structure. I'll look into making it a little less painful for users to change the port that the extension is communicating on. Thanks for your interest in the project.

**Comment by BjarneJensen** [comment]
It really should have been the first thing I checked. I guess I was
partially surprised by how easy it was to set up, so I thought it must have
been something more complicated. Thank you for your contribution to the
community.
